- name: Установка OpenVPN и локального DNS
  hosts: openvpn_server
  become: true
  tasks:
    - name: Обновить менеджер пакетов apt
      ansible.builtin.apt:
        update_cache: yes

    - name: Установить необходимые пакеты для OpenVPN, DNS, создания ключей подключения в VPN
      ansible.builtin.apt:
        name:
          - openvpn
          - easy-rsa
          - dnsmasq
        state: present

    - name: Создать каталог для ключей
      ansible.builtin.file:
        path: /etc/openvpn/easy-rsa
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Копировать файлы Easy-RSA
      ansible.builtin.copy:
        src: /usr/share/easy-rsa/
        dest: /etc/openvpn/easy-rsa
        remote_src: yes

    - name: Создать vars файл
      ansible.builtin.copy:
        dest: /etc/openvpn/easy-rsa/vars
        content: |
          set_var EASYRSA_ALGO "ec"
          set_var EASYRSA_DIGEST "sha512"
          set_var EASYRSA_KEY_SIZE 4096
          set_var EASYRSA_REQ_COUNTRY "RU"
          set_var EASYRSA_REQ_PROVINCE "Moscow"
          set_var EASYRSA_REQ_CITY "Moscow"
          set_var EASYRSA_REQ_ORG "MyVPN"
          set_var EASYRSA_REQ_EMAIL "ikpolux@mail.ru"
          set_var EASYRSA_REQ_OU "IT"
          set_var EASYRSA_BATCH "1"

    - name: Инициализация PKI
      ansible.builtin.command: /etc/openvpn/easy-rsa/easyrsa init-pki
      args:
        chdir: /etc/openvpn/easy-rsa

    - name: Создание CA
      ansible.builtin.command: /etc/openvpn/easy-rsa/easyrsa build-ca nopass
      args:
        chdir: /etc/openvpn/easy-rsa

    - name: Генерация серверного ключа и сертификата
      ansible.builtin.command: /etc/openvpn/easy-rsa/easyrsa build-server-full server nopass
      args:
        chdir: /etc/openvpn/easy-rsa

    - name: Получаем информацию по файлу /etc/openvpn/ca.crt
      ansible.builtin.stat:
        path: /etc/openvpn/ca.crt
      register: vpn_certificate

    - name: |
       Копирование файлов в директорию OpenVPN, только когда сертификаты не были уже выпущены,
        чтобы не обновить сертификаты при повторном запуске скрипта
      shell: |
        cp /etc/openvpn/easy-rsa/pki/ca.crt /etc/openvpn/
        cp /etc/openvpn/easy-rsa/pki/private/ca.key /etc/openvpn/
        cp /etc/openvpn/easy-rsa/pki/private/server.key /etc/openvpn/
        cp /etc/openvpn/easy-rsa/pki/issued/server.crt /etc/openvpn/
      when: not vpn_certificate.stat.exists

    - name: Настроить dnsmasq
      ansible.builtin.copy:
        dest: /etc/dnsmasq.conf
        content: |
          listen-address=10.8.0.1
          interface=tun0
          domain=myvpn.local
          expand-hosts
          local=/myvpn.local/
          address=/server.myvpn.local/10.8.0.1
          address=/upikoth.myvpn.local/10.8.0.2
          server=8.8.8.8
          server=8.8.4.4

    - name: Настроить конфигурацию сервера OpenVPN
      ansible.builtin.copy:
        dest: /etc/openvpn/server.conf
        content: |
          port 1194
          proto udp
          dev tun
          ca /etc/openvpn/ca.crt
          cert /etc/openvpn/server.crt
          key /etc/openvpn/server.key
          dh /etc/openvpn/dh2048.pem
          topology subnet
          server 10.8.0.0 255.255.255.0
          ifconfig-pool-persist /var/log/openvpn/ipp.txt
          keepalive 10 120
          persist-key
          persist-tun
          status /var/log/openvpn-status.log
          verb 5
          push "dhcp-option DNS 10.8.0.1"
          push "dhcp-option DOMAIN myvpn.local"
          log /var/log/openvpn.log
          data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305
          auth SHA256

    - name: Получаем информацию по файлу /etc/openvpn/dh2048.pem
      ansible.builtin.stat:
        path: /etc/openvpn/dh2048.pem
      register: dh_file

    - name: Создание DH файла
      ansible.builtin.command:
        cmd: "openssl dhparam -out /etc/openvpn/dh2048.pem 2048"
        creates: /etc/openvpn/dh2048.pem
      when: not dh_file.stat.exists

    - name: Разрешить переадресацию пакетов
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv4.ip_forward = 1"
        state: present

    - name: Применить изменения sysctl
      ansible.builtin.command: sysctl -p

    - name: Настроить iptables
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        jump: MASQUERADE
        out_interface: eth0
        source: 10.8.0.0/24
      notify:
        - save_iptables

    - name: Выключить systemd-resolved, чтобы освободить 53 порт для dnsmasq
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: no

    - name: Указать dnsmasq в качестве dns на сервере
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 10.8.0.1
          options edns0 trust-ad
          search .

    - name: Перезапустить OpenVPN
      ansible.builtin.systemd:
        name: openvpn@server
        state: restarted
        enabled: yes

    - name: Перезапустить dnsmasq
      ansible.builtin.systemd:
        name: dnsmasq
        state: restarted
        enabled: yes

  handlers:
    - name: save_iptables
      ansible.builtin.command: iptables-save > /etc/iptables/rules.v4
